apiVersion: v1
# KIND: Pod ﾃｩ a unidade bﾃ｡sica de deployment no Kubernetes
# Um Pod pode conter um ou mais containers que compartilham rede e storage
kind: Pod
metadata:
  # NAME: Identificador ﾃｺnico do Pod dentro do namespace
  # Deve ser DNS-compatible: minﾃｺsculas, hﾃｭfens, nﾃｺmeros, mﾃ｡ximo 253 caracteres
  name: giropops-strigus-desafio2
  # NAMESPACE: Espaﾃｧo isolado para agrupar recursos relacionados
  # 'default' ﾃｩ usado quando nenhum namespace especﾃｭfico ﾃｩ definido
  namespace: default
  # LABELS: Metadados para identificar e selecionar recursos
  # Usados por Services, Selectors e outras ferramentas Kubernetes
  labels:
    app: nginx                 # Aplicaﾃｧﾃ｣o principal - servidor web Nginx
    version: "2.0"             # Versﾃ｣o desta configuraﾃｧﾃ｣o especﾃｭfica
    environment: development   # Ambiente de desenvolvimento/testes
    team: devops               # Equipe responsﾃ｡vel pela operaﾃｧﾃ｣o
  # ANNOTATIONS: Metadados descritivos para documentaﾃｧﾃ｣o e ferramentas
  # Nﾃ｣o sﾃ｣o usados para seleﾃｧﾃ｣o de objetos, apenas para informaﾃｧﾃ｣o
  annotations:
    description: "Pod com Nginx e Alpine - Corrigido erro 403 com conteﾃｺdo estﾃ｡tico"
    created-by: "devgs8"
    issue-resolved: "403 Forbidden - Adicionado index.html e ajustado volume sharing"
    documentation: "https://kubernetes.io/docs/concepts/workloads/pods/"

spec:
  # RESTART POLICY: Comportamento do Kubernetes quando containers terminam
  # - Always: Reinicia automaticamente (padrﾃ｣o para serviﾃｧos web)
  # - OnFailure: Reinicia apenas em caso de falha
  # - Never: Nunca reinicia
  restartPolicy: Always

  # CONTAINERS: Lista de containers executando no mesmo Pod
  # Containers no mesmo Pod compartilham:
  # - Namespace de rede (mesmo IP, comunicaﾃｧﾃ｣o via localhost)
  # - Volumes de armazenamento
  # - Ciclo de vida (iniciam e param juntos)
  containers:
  # CONTAINER 1: Servidor Web Nginx
  - name: nginx-container      # Nome ﾃｺnico para referﾃｪncia dentro do Pod
    image: nginx:latest        # Imagem Docker oficial do Nginx
    # IMAGE PULL POLICY: Controla quando baixar a imagem do registry
    # - IfNotPresent: Baixa apenas se nﾃ｣o existir localmente (otimiza deployments)
    # - Always: Sempre baixa a imagem (garante versﾃ｣o mais recente)
    # - Never: Usa apenas imagem local (para ambientes offline)
    imagePullPolicy: IfNotPresent
    
    # PORTS: Portas que o container expﾃｵe (informativo para Services)
    ports:
    - name: http               # Nome descritivo para referﾃｪncia em Services
      containerPort: 80        # Porta TCP onde Nginx escuta requisiﾃｧﾃｵes HTTP
      protocol: TCP            # Protocolo de transporte (TCP para HTTP)

    # RESOURCES: Requisiﾃｧﾃｵes e limites de recursos computacionais
    resources:
      # REQUESTS: Recursos mﾃｭnimos reservados - Kubernetes usa para scheduling
      requests:
        cpu: "100m"            # 100 milicores = 0.1 vCPU (mﾃｭnimo para operaﾃｧﾃ｣o)
        memory: "64Mi"         # 64 Mebibytes de RAM (1 Mi = 1024^2 bytes)
      # LIMITS: Mﾃ｡ximo de recursos que o container pode consumir
      limits:
        cpu: "500m"            # 500 milicores = 0.5 vCPU (previne uso excessivo)
        memory: "256Mi"        # 256 Mebibytes de RAM

    # LIVENESS PROBE: Verifica se a aplicaﾃｧﾃ｣o estﾃ｡ viva e responsiva
    # Se falhar, Kubernetes reinicia o container apﾃｳs failureThreshold
    livenessProbe:
      httpGet:                 # Faz requisiﾃｧﾃ｣o HTTP GET para verificar saﾃｺde
        path: /index.html      # CORREﾃﾃグ: Verifica arquivo especﾃｭfico em vez de diretﾃｳrio
        port: 80
      initialDelaySeconds: 15  # Aguarda 15s apﾃｳs start antes da primeira verificaﾃｧﾃ｣o
      periodSeconds: 20        # Executa verificaﾃｧﾃ｣o a cada 20 segundos
      timeoutSeconds: 5        # Timeout de 5 segundos para a requisiﾃｧﾃ｣o
      successThreshold: 1      # 1 verificaﾃｧﾃ｣o bem-sucedida marca como saudﾃ｡vel
      failureThreshold: 3      # 3 falhas consecutivas marca como nﾃ｣o saudﾃ｡vel

    # READINESS PROBE: Verifica se a aplicaﾃｧﾃ｣o estﾃ｡ pronta para receber trﾃ｡fego
    # Se falhar, o Pod ﾃｩ removido dos Service Endpoints
    readinessProbe:
      httpGet:
        path: /index.html      # CORREﾃﾃグ: Verifica arquivo especﾃｭfico
        port: 80
      initialDelaySeconds: 5   # Verifica rﾃ｡pido se estﾃ｡ pronto (5 segundos)
      periodSeconds: 10        # Verifica a cada 10 segundos
      timeoutSeconds: 3        # Timeout menor para readiness (3 segundos)

    # VOLUME MOUNTS: Pontos onde volumes sﾃ｣o montados no filesystem do container
    volumeMounts:
    - name: shared-data        # Referﾃｪncia ao volume definido na seﾃｧﾃ｣o volumes:
      mountPath: /usr/share/nginx/html  # Diretﾃｳrio onde Nginx serve arquivos estﾃ｡ticos
      readOnly: false          # Container pode ler e escrever neste volume

  # CONTAINER 2: Alpine Linux - Container utilitﾃ｡rio
  - name: alpine-container     # Nome ﾃｺnico para o segundo container
    image: alpine:latest       # Imagem Alpine Linux (minimalista, ~5MB)
    imagePullPolicy: IfNotPresent
    
    # COMMAND E ARGS: Substitui o comando padrﾃ｣o da imagem
    command: ["/bin/sh"]       # Executa shell script
    args:                      # Argumentos passados para o shell
    - "-c"
    # CORREﾃﾃグ: Script expandido para criar index.html E escrever logs
    - |
      mkdir -p /shared-data
      # Criar arquivo index.html para Nginx servir
      cat > /shared-data/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head>
          <title>Giropops Strigus - Desafio Day 2</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 40px; background: #f0f0f0; }
              .container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
              h1 { color: #333; }
              .info { background: #e7f3ff; padding: 15px; border-radius: 5px; margin: 20px 0; }
          </style>
      </head>
      <body>
          <div class="container">
              <h1>噫 Giropops Strigus - Kubernetes Day 2</h1>
              <div class="info">
                  <p><strong>Pod:</strong> giropops-strigus-desafio2-corrigido</p>
                  <p><strong>Containers:</strong> Nginx + Alpine</p>
                  <p><strong>Volume:</strong> EmptyDir compartilhado</p>
                  <p><strong>Status:</strong> 笨 Funcionando perfeitamente!</p>
              </div>
              <p>Esta pﾃ｡gina ﾃｩ servida pelo Nginx e o conteﾃｺdo ﾃｩ criado pelo container Alpine atravﾃｩs de um volume EmptyDir compartilhado.</p>
          </div>
      </body>
      </html>
      EOF
      # Escrever logs continuamente
      while true; do echo "$(date): Container Alpine ativo - Volume compartilhado funcionando" >> /shared-data/log.txt; sleep 30; done

    # RESOURCES: Requisiﾃｧﾃｵes menores para container utilitﾃ｡rio
    resources:
      requests:
        cpu: "50m"             # 50 milicores - suficiente para tarefas leves
        memory: "32Mi"         # 32 Mebibytes - Alpine ﾃｩ muito leve
      limits:
        cpu: "100m"            # 100 milicores - limite mﾃ｡ximo
        memory: "64Mi"         # 64 Mebibytes - limite de memﾃｳria

    # VOLUME MOUNTS: Monta o mesmo volume compartilhado com Nginx
    volumeMounts:
    - name: shared-data        # Mesmo volume do Nginx
      mountPath: /shared-data  # Caminho diferente no Alpine
      readOnly: false          # Permite escrita - Alpine cria arquivos aqui

  # VOLUMES: Definiﾃｧﾃ｣o dos volumes disponﾃｭveis para montagem
  volumes:
  # VOLUME 1: EmptyDir - Volume temporﾃ｡rio que dura enquanto o Pod existir
  - name: shared-data          # Nome referenciado nos volumeMounts
    emptyDir:                  # Tipo EmptyDir - diretﾃｳrio vazio criado quando Pod inicia
      # Dados persistem durante a vida do Pod, mas sﾃ｣o perdidos quando Pod ﾃｩ deletado
      # Ideal para compartilhamento de dados entre containers no mesmo Pod
      medium: ""               # "" = disco (padrﾃ｣o), "Memory" = RAM (mais rﾃ｡pido)
      sizeLimit: 500Mi         # Limite opcional de tamanho (500 Mebibytes)

  # CONFIGURAﾃﾃ髭S DE REDE
  hostNetwork: false           # Se true, usa rede do node host (nﾃ｣o recomendado)
  hostPID: false               # Se true, compartilha PID namespace com host
  hostIPC: false               # Se true, compartilha IPC namespace com host

  # CONFIGURAﾃﾃグ DNS
  dnsPolicy: ClusterFirst      # Polﾃｭtica de resoluﾃｧﾃ｣o DNS
  # - ClusterFirst: Encaminha DNS para cluster DNS antes de servidores externos
  # - Default: Herda configuraﾃｧﾃ｣o DNS do node
  # - None: Configuraﾃｧﾃ｣o personalizada via dnsConfig
